// ===========================================
// DealFlow360 - Database Seed Orchestrator
// ===========================================
// PHASE 0: Main seed script - FROZEN after Phase 0.
// Do not edit this file individually.
// Each dev adds their module's seed data in their own files.
// ===========================================

import { PrismaClient } from '@prisma/client';
import { seedUsers } from './seeds/userSeed.js';
import { seedCatalog } from './seeds/catalogSeed.js';
import { seedQuotations } from './seeds/quotationSeed.js';

const prisma = new PrismaClient();

async function main() {
  console.log('Starting database seed...\n');

  try {
    // 1. Seed shared users and customers (Phase 0)
    console.log('--- Seeding Users & Customers ---');
    await seedUsers(prisma);
    console.log('Users & Customers seeded successfully\n');

    // 2. Seed catalog data - Dev B's responsibility
    console.log('--- Seeding Catalog (Products, Warehouses, Price Lists) ---');
    await seedCatalog(prisma);
    console.log('Catalog seeded successfully\n');

    // 3. Seed quotation/approval config - Dev A's responsibility
    console.log('--- Seeding Quotation Config (Discount Tiers, Approval Chains) ---');
    await seedQuotations(prisma);
    console.log('Quotation config seeded successfully\n');

    console.log('Database seed completed successfully!');
  } catch (error) {
    console.error('Seed error:', error);
    throw error;
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
