// ===========================================
// DealFlow360 - Database Seed Orchestrator
// ===========================================
// PHASE 0: Main seed script - FROZEN after Phase 0.
// Do not edit this file individually.
// Each dev adds their module's seed data in their own files.
// ===========================================

import { PrismaClient } from '@prisma/client';
import { seedUsers } from './seeds/userSeed.js';
import { seedCatalog } from './seeds/catalogSeed.js';
import { seedQuotations } from './seeds/quotationSeed.js';
import { seedMassiveData } from './seeds/massiveSeed.js';

const prisma = new PrismaClient();

// Check if massive seed is requested via command line argument
const runMassiveSeed = process.argv.includes('--massive') || process.argv.includes('-m');

async function main() {
  console.log('Starting database seed...\n');

  try {
    // 1. Seed shared users and customers (Phase 0)
    console.log('--- Seeding Users & Customers ---');
    await seedUsers(prisma);
    console.log('Users & Customers seeded successfully\n');

    // 2. Seed catalog data - Dev B's responsibility
    console.log('--- Seeding Catalog (Products, Warehouses, Price Lists) ---');
    await seedCatalog(prisma);
    console.log('Catalog seeded successfully\n');

    // 3. Seed quotation/approval config - Dev A's responsibility
    console.log('--- Seeding Quotation Config (Discount Tiers, Approval Chains) ---');
    await seedQuotations(prisma);
    console.log('Quotation config seeded successfully\n');

    // 4. Run massive seed if requested (250+ entries per table)
    if (runMassiveSeed) {
      console.log('--- Running Massive Data Seed (250+ per table) ---');
      await seedMassiveData(prisma);
      console.log('Massive data seed completed successfully\n');
    }

    console.log('Database seed completed successfully!');
    if (!runMassiveSeed) {
      console.log('TIP: Run with --massive or -m flag to seed 250+ entries per table');
    }
  } catch (error) {
    console.error('Seed error:', error);
    throw error;
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
